### ISSUE TITLE
Pressing enter should skip the option

### ISSUE THREAD

**Issue by electerious** [BetaHuhn/ackee-report#8]
**Describe the bug**

`ackee-report` asks to input a few values when you use it for the first time. I don't have an email host, username and password as I wanted to use the RSS generator. It would be great if there's a way to skip them.

**Expected behavior**

Pressing enter should skip the option.

**Screenshots**

I've entered a space in order to skip them.

![Screenshot 2020-11-21 at 19 35 53](https://user-images.githubusercontent.com/499088/99884746-caf46a00-2c30-11eb-9f0d-624940bf012e.png)

**Comment by BetaHuhn** [comment]
You are right, that should totally be an option now that ackee-report supports different outputs!

Going to fix this tomorrow👍

**Comment by BetaHuhn** [comment]
This was fixed in [`v0.6.2`](https://github.com/BetaHuhn/ackee-report/releases/tag/v0.6.2).
